<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TIC5DM4" failures="1" tests="7" name="com.App.Testcases.testrunner" time="77.315" errors="0" timestamp="2024-08-27T13:27:12 IST" skipped="0">
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="12.242"/>
  <system-out/>
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="12.442"/>
  <system-out/>
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="7.618"/>
  <system-out/>
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="12.866"/>
  <system-out/>
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="9.181"/>
  <system-out/>
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="12.457"/>
  <system-out/>
  <testcase classname="com.App.Testcases.testrunner" name="runScenario" time="10.509">
    <failure message="Login Failed expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login Failed expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.App.Testcases.loginTestCase.he_enters_and(loginTestCase.java:40)
at âœ½.he enters "pathanasifkhan461@gmail.com" and "Assm@7866"(file:///C:/Users/Administrator/eclipse-workspace/Cucumber_DemoWebshop/src/test/resources/features/login.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.App.Testcases.testrunner -->
