<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TIC5DM4" failures="1" tests="7" name="Test" time="77.807" errors="0" timestamp="2024-08-27T13:27:12 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.866"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.457"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.242"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="10.509">
    <failure type="java.lang.AssertionError" message="Login Failed expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]">
      <![CDATA[java.lang.AssertionError: Login Failed expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]
at com.App.Testcases.loginTestCase.he_enters_and(loginTestCase.java:40)
at âœ½.he enters "pathanasifkhan461@gmail.com" and "Assm@7866"(file:///C:/Users/Administrator/eclipse-workspace/Cucumber_DemoWebshop/src/test/resources/features/login.feature:6)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.181"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.442"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.618"/>
</testsuite> <!-- Test -->
