<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-09T13:30:27Z" name="Default suite" finished-at="2024-08-09T13:30:36Z" duration-ms="9602">
    <groups>
    </groups>
    <test started-at="2024-08-09T13:30:27Z" name="Default test" finished-at="2024-08-09T13:30:36Z" duration-ms="9602">
      <class name="validCredentials">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:26Z" name="beforeSuite" finished-at="2024-08-09T19:00:27Z" duration-ms="363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:27Z" name="setUp" finished-at="2024-08-09T19:00:36Z" duration-ms="9544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="f()[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:36Z" name="f" finished-at="2024-08-09T19:00:36Z" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:36Z" name="getResult" finished-at="2024-08-09T19:00:36Z" duration-ms="0" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=f status=SUCCESS method=ReportGenerator.f()[pri:0, instance:validCredentials@401f7633] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "ReportGenerator.test" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "ReportGenerator.test" is null
	at ReportGenerator.getResult(ReportGenerator.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method signature="validCredent()[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:36Z" name="validCredent" finished-at="2024-08-09T19:00:36Z" duration-ms="3" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredent -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:36Z" name="getResult" finished-at="2024-08-09T19:00:36Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:36Z" name="afterClass" finished-at="2024-08-09T19:00:36Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:validCredentials@401f7633]" started-at="2024-08-09T19:00:36Z" name="afterSuite" finished-at="2024-08-09T19:00:36Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- validCredentials -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
